config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', as: :root
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :new, :create, :update, :show]
  resources :accounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :accounting_periods, only: [:index, :new, :create, :update, :show, :destroy]
  resources :transaction_types, only: [:index, :new, :create, :update, :show, :destroy]
  resources :gl_mappings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_makes, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_models, only: [:index, :new, :create, :update, :show, :destroy]
  resources :images, only: [:index, :new, :create, :update, :show, :destroy]

  resources :product_discounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :product_pricings, only: [:index, :new, :create, :update, :show, :destroy]

  resources :member_profiles, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_cars, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_contacts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_stickers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_photos, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_car_photos, only: [:index, :new, :create, :update, :show, :destroy]
    
  resources :sequences, only: [:index, :new, :create, :update, :show, :destroy]
  resources :general_ledgers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :inventories, only: [:index, :new, :create, :update, :show, :destroy]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sparesandaccessories, only: [:index, :new, :create, :update, :show, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/email_sent', to: 'email_sent#index', as: :email_sent
  get '/activate/:activation_code', to: 'activations#create', as: :activate
  get '/admin', to: 'administration#index', as: :admin
  get '/admin/listusers', to: 'administration#listusers', as: :listusers
  post '/admin/toggleactive', to: 'administration#toggleactive', as: :toggleactive
  post '/admin/toggleapprove', to: 'administration#toggleapprove', as: :toggleapprove
  post '/admin/toggleconfirm', to: 'administration#toggleconfirm', as: :toggleconfirm
  get '/gallery', to: 'gallery#index', as: :gallery
  get '/search/:object', to: 'search#search', as: :genericsearch
  get '/accountingpanel', to: 'accountingpanel#index', as: :accountingpanel
  get '/customer_view', to: 'sparesandaccessories#customer_view', as: :customer_view
  delete '/delete_pricing/:id', to: 'products#delete_pricing', as: :delete_pricing
  patch '/toggle_discount_active/:id', to: 'products#toggle_discount_active', as: :toggle_discount_active
  delete '/delete_discount/:id', to: 'products#delete_discount', as: :delete_discount
  delete '/delete_contact/:id', to: 'member_profiles#delete_contact', as: :delete_contact
  delete '/delete_profile_car/:id', to: 'member_profiles#delete_profile_car', as: :delete_profile_car
  delete 'delete_sticker/:id', to: 'member_profiles#delete_sticker', as: :delete_sticker
  get '/profile_car_view', to: 'member_profiles#profile_car_view', as: :profile_car_view
  

end

app/controllers/accountingpanel_controller.rb
class AccountingpanelController < ApplicationController
  #filter_resource_access
  def index
    @accounts = Account.paginate(:page => params[:page], :per_page => 10)
    @accounting_periods = AccountingPeriod.paginate(:page => params[:page], :per_page => 10)
    @general_ledgers = GeneralLedger.paginate(:page => params[:page], :per_page => 10)
    @transaction_types = TransactionType.paginate(:page => params[:page], :per_page => 10)
    @gl_mappings = GlMapping.paginate(:page => params[:page], :per_page => 10)
   
  end
end

app/views/accountingpanel/_accountingbody.html.erb
<div class="col-xs-7 col-sm-6 col-lg-8" >
<% if params[:custparam].to_s == "accounts".to_s  %>

	<% permitted_to? :manage, :accounts do %>
		<%= render 'accounts/index' %>
	<% end %>
	
<% elsif params[:custparam].to_s == "accounting_period".to_s  %>
	<% permitted_to? :manage, :accounting_periods do %>
		<%= render 'accounting_periods/index' %>
	<% end %>
<% elsif params[:custparam].to_s == "transaction_types".to_s  %>
	<% permitted_to? :manage, :transaction_types do %>
		<%= render 'transaction_types/index' %>
	<% end %>
<% elsif params[:custparam].to_s == "gl_mappings".to_s  %>
	<% permitted_to? :manage, :gl_mappings do %>
		<%= render 'gl_mappings/index' %>
	<% end %>	
<% else %>
	<% permitted_to? :manage, :accounting_periods do %>
		<%= render 'accounting_periods/index' %>
	<% end %>
<% end %>


</div>

app/views/accountingpanel/_accountingnav.html.erb
<h2>Accounting Panel</h2>
<div class="col-xs-3 col-sm-4 col-lg-2" >

<ul class="nav nav-pills nav-stacked">
   <li><%= link_to 'Accounts', accountingpanel_url(:custparam => 'accounts') %></li>
   <li><%= link_to 'Accounting Periods', accountingpanel_url(:custparam => 'accounting_period') %></li>
   <li><%= link_to 'Transaction Types', accountingpanel_url(:custparam => 'transaction_types') %></li>
   <li><%= link_to 'GL Transaction Mapping', accountingpanel_url(:custparam => 'gl_mappings') %></li>
</ul>

</div>
<script>
    $(".nav li").on("click", function() {
      $(".nav li").removeClass("hocwhite");
      $(this).addClass("hocwhite");
    });
</script>

app/views/accountingpanel/index.html.erb
<% permitted_to? :manage, :accounts do %>
	<%= render 'accountingpanel/accountingnav' %>
	<%= render 'accountingpanel/accountingbody' %>
<% end %>