config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', as: :root
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :new, :create, :update, :show]
  resources :accounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :accounting_periods, only: [:index, :new, :create, :update, :show, :destroy]
  resources :transaction_types, only: [:index, :new, :create, :update, :show, :destroy]
  resources :gl_mappings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_makes, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_models, only: [:index, :new, :create, :update, :show, :destroy]
  resources :images, only: [:index, :new, :create, :update, :show, :destroy]

  resources :product_discounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :product_pricings, only: [:index, :new, :create, :update, :show, :destroy]

  resources :member_profiles, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_cars, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_contacts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_stickers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_photos, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_car_photos, only: [:index, :new, :create, :update, :show, :destroy]
    
  resources :sequences, only: [:index, :new, :create, :update, :show, :destroy]
  resources :general_ledgers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :inventories, only: [:index, :new, :create, :update, :show, :destroy]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sparesandaccessories, only: [:index, :new, :create, :update, :show, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/email_sent', to: 'email_sent#index', as: :email_sent
  get '/activate/:activation_code', to: 'activations#create', as: :activate
  get '/admin', to: 'administration#index', as: :admin
  get '/admin/listusers', to: 'administration#listusers', as: :listusers
  post '/admin/toggleactive', to: 'administration#toggleactive', as: :toggleactive
  post '/admin/toggleapprove', to: 'administration#toggleapprove', as: :toggleapprove
  post '/admin/toggleconfirm', to: 'administration#toggleconfirm', as: :toggleconfirm
  get '/gallery', to: 'gallery#index', as: :gallery
  get '/search/:object', to: 'search#search', as: :genericsearch
  get '/accountingpanel', to: 'accountingpanel#index', as: :accountingpanel
  get '/customer_view', to: 'sparesandaccessories#customer_view', as: :customer_view
  delete '/delete_pricing/:id', to: 'products#delete_pricing', as: :delete_pricing
  patch '/toggle_discount_active/:id', to: 'products#toggle_discount_active', as: :toggle_discount_active
  delete '/delete_discount/:id', to: 'products#delete_discount', as: :delete_discount
  delete '/delete_contact/:id', to: 'member_profiles#delete_contact', as: :delete_contact
  delete '/delete_profile_car/:id', to: 'member_profiles#delete_profile_car', as: :delete_profile_car
  delete 'delete_sticker/:id', to: 'member_profiles#delete_sticker', as: :delete_sticker
  get '/profile_car_view', to: 'member_profiles#profile_car_view', as: :profile_car_view
  

end

app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base
  belongs_to :vehicle_make
  belongs_to :product
  attr_reader :vehicle_make
  attr_writer :vehicle_make
  def self.search(query, page = 1)
    if(!query.nil? && !query.empty?)
      wildcard_search = "%#{query}%"
      psttmt = where("name LIKE ? ", wildcard_search)
      psttmt = psttmt.page(page)
      psttmt = psttmt.per_page(5)
    end
  end

  def to_s
    "Make: #{name} Year: #{year}"
  end
end

app/controllers/vehicle_models_controller.rb
class VehicleModelsController < ApplicationController
  filter_resource_access
  def index
    @vehicle_models = VehicleModel.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @vehicle_model = VehicleModel.find(params[:id])
    @vehicle_model =  populate_vehicle_make @vehicle_model
  end

  def new
    @vehicle_model = VehicleModel.new
  end

  def edit
    @vehicle_model = VehicleModel.find(params[:id])
    @vehicle_model =  populate_vehicle_make @vehicle_model
  end

  def create
    @vehicle_model = VehicleModel.new(vehicle_make_params)
    @vehicle_make = add_model_to_make @vehicle_model
    if @vehicle_model.save
      flash[:info] = "Vehicle Model  - \"#{@vehicle_model.name}\" - has been created."
      redirect_to vehicle_models_url
    else
      render 'new'
    end
  end

  def update
    @vehicle_model = VehicleModel.find(params[:id])
    if @vehicle_model.update_attributes(vehicle_make_params)
      flash[:success] = "Vehicle Model  \"#{@vehicle_model.name}\"  successfully updated!"
      redirect_to vehicle_models_url
    else
      render :edit
    end
  end

  def destroy
    @vehicle_model = VehicleModel.find(params[:id])
    if @vehicle_model
      @vehicle_model.destroy
    end
    redirect_to vehicle_models_url
  end

  private

  def add_model_to_make(vehicle_model)

    vehile_make = VehicleMake.find(vehicle_model.vehicle_make_id)
    if(!vehile_make.nil? && vehile_make.vehicle_models.nil?)
      vehile_make.vehicle_models = []
    end
    vehile_make.vehicle_models << vehicle_model
    vehile_make.save

    vehicle_model

  end

  private

  def vehicle_make_params
    params.require(:vehicle_model).permit(:name, :year, :vehicle_make_id)
  end

  private

  def populate_vehicle_make(vehicle_model)
    vehicle_model.vehicle_make_id  = vehicle_model.vehicle_make_id
    vehicle_model
  end
end

app/views/vehicle_models/_back.html.erb
<p>
<%= link_to(raw("<span class='glyphicon glyphicon-arrow-left'> Back </span>"),vehicle_models_url,{ :class => 'btn btn-primary'})  %>
</p>

app/views/vehicle_models/_form.html.erb
<%= form_for @vehicle_model do |f| %>
	
	<%= render 'shared/errors', object: @vehicle_model %>
  
  <p>
    <%= f.text_field :name,  class: "form-control", placeholder: "Name", required: true %>
  </p>
  <p>
    <%= f.number_field :year,  class: "form-control", placeholder: "Year", min: "1900", max: "2060"  %>
  </p>
  <p>
    <%= f.collection_select :vehicle_make_id, VehicleMake.all, :id,:name, {prompt: "Select Vehicle Make"}, {class: "form-control"} %>
  </p>
  <p><%= f.submit "Save", class: "btn btn-lg btn-primary btn-block btn-signin" %></p>
<% end %>

app/views/vehicle_models/_index.html.erb
<% permitted_to? :manage, :vehicle_models do %>
	<%= link_to 'New Vehicle Model', new_vehicle_model_path %>

<table class="table table-hover">
  <tr>
  	<th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th></th>
  </tr>
 
  <% @vehicle_models.each do |vehicle_model| %>
    <tr>
      <td><%= VehicleMake.find(vehicle_model.vehicle_make_id).name %></td>
      <td><%= vehicle_model.name %></td>
      <td><%= vehicle_model.year %></td>
      <% permitted_to? :manage, :vehicle_models do %>
      	<td><%= link_to 'Edit', vehicle_model, method: :get %></td>
      	<td><%= link_to 'Delete', vehicle_model, method: :delete,
      	data: { confirm: 'Are you sure you want to  delete the vehicle model \''+vehicle_model.name+'\'?' }  %></td>
      <% end %>
      
    </tr>
  <% end %>
</table>
<p>
<%= will_paginate(@vehicle_models, :previous_label => "&laquo;", :next_label => "&raquo;", :class=>"small-font", :outer_window => 1, :inner_window => 0, :class=>"small-font", :outer_window => 1, :inner_window => 0) %>
<%= page_entries_info @vehicle_models %>
</p>

<% end %>

app/views/vehicle_models/edit.html.erb
<%= render 'back' %>
<%= render 'form' %>