config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', as: :root
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :new, :create, :update, :show]
  resources :accounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :accounting_periods, only: [:index, :new, :create, :update, :show, :destroy]
  resources :transaction_types, only: [:index, :new, :create, :update, :show, :destroy]
  resources :gl_mappings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_makes, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_models, only: [:index, :new, :create, :update, :show, :destroy]
  resources :images, only: [:index, :new, :create, :update, :show, :destroy]

  resources :product_discounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :product_pricings, only: [:index, :new, :create, :update, :show, :destroy]

  resources :member_profiles, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_cars, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_contacts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_stickers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_photos, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_car_photos, only: [:index, :new, :create, :update, :show, :destroy]
    
  resources :sequences, only: [:index, :new, :create, :update, :show, :destroy]
  resources :general_ledgers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :inventories, only: [:index, :new, :create, :update, :show, :destroy]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sparesandaccessories, only: [:index, :new, :create, :update, :show, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/email_sent', to: 'email_sent#index', as: :email_sent
  get '/activate/:activation_code', to: 'activations#create', as: :activate
  get '/admin', to: 'administration#index', as: :admin
  get '/admin/listusers', to: 'administration#listusers', as: :listusers
  post '/admin/toggleactive', to: 'administration#toggleactive', as: :toggleactive
  post '/admin/toggleapprove', to: 'administration#toggleapprove', as: :toggleapprove
  post '/admin/toggleconfirm', to: 'administration#toggleconfirm', as: :toggleconfirm
  get '/gallery', to: 'gallery#index', as: :gallery
  get '/search/:object', to: 'search#search', as: :genericsearch
  get '/accountingpanel', to: 'accountingpanel#index', as: :accountingpanel
  get '/customer_view', to: 'sparesandaccessories#customer_view', as: :customer_view
  delete '/delete_pricing/:id', to: 'products#delete_pricing', as: :delete_pricing
  patch '/toggle_discount_active/:id', to: 'products#toggle_discount_active', as: :toggle_discount_active
  delete '/delete_discount/:id', to: 'products#delete_discount', as: :delete_discount
  delete '/delete_contact/:id', to: 'member_profiles#delete_contact', as: :delete_contact
  delete '/delete_profile_car/:id', to: 'member_profiles#delete_profile_car', as: :delete_profile_car
  delete 'delete_sticker/:id', to: 'member_profiles#delete_sticker', as: :delete_sticker
  get '/profile_car_view', to: 'member_profiles#profile_car_view', as: :profile_car_view
  

end

app/models/product_pricing.rb
class ProductPricing < ActiveRecord::Base
  belongs_to :product

  def self.findActivePricing(product_id)
    where("product_id = ?  and (? between date_from and date_to) ", product_id, Date.today ).order("date_from ASC, date_to ASC").first
  end
end

app/controllers/product_pricings_controller.rb
class ProductPricingsController < ApplicationController
  filter_resource_access
  def index
    @product_pricings = ProductPricing.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @product_pricing = ProductPricing.find(params[:id])
  end

  def new
    @product_pricing = ProductPricing.new
  end

  def edit
    @product_pricing = ProductPricing.find(params[:id])
  end

  def create
    @product_pricing = ProductPricing.new(account_params)
    if @product_pricing.save
      flash[:info] = "Product Pricing created."
      redirect_to product_pricings_url
    else
      render 'new'
    end
  end

  def update
    @product_pricing = ProductPricing.find(params[:id])
    if @product_pricing.update_attributes(account_params)
      flash[:success] = "Product Pricing successfully updated!"
      redirect_to product_pricings_url
    else
      render :edit
    end
  end

  def destroy
    @product_pricing = ProductPricing.find(params[:id])
    product = Product.find(@product_pricing.product_id)
    if @product_pricing
      @product_pricing.destroy
    end
    redirect_to product
  end

  private

  def account_params
    params.require(:product_pricing).permit(:product_id, :from_date, :to_date, :amount)
  end
end

app/views/product_pricings/_back.html.erb
<p>
<%= link_to(raw("<span class='glyphicon glyphicon-arrow-left'> Back </span>"),product_pricings_url,{ :class => 'btn btn-primary'})  %>
</p>

app/views/product_pricings/_form.html.erb
<%= form_for @product_pricing do |f| %>
	
	<%= render 'shared/errors', object: @product_pricing %>
  
  <p>
    <%= f.text_field :name,  class: "form-control", placeholder: "Name", required: true %>
  </p>
  <p>
    <%= f.text_field :code, value: getSeq("AC"),  class: "form-control", placeholder: "Ac. Code", required: true %>
  </p>
  <p>
    <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
  </p>
  <p><%= f.submit "Save", class: "btn btn-lg btn-primary btn-block btn-signin" %></p>
<% end %>

app/views/product_pricings/_index.html.erb
<% permitted_to? :manage, :product_pricings do %>
	<%= link_to 'New Pricing', new_product_pricing_path %>

<table class="table table-hover">
  <tr>
    <th>Product</th>
    <th>Starting</th>
    <th>Ending</th>
    <th>Amount</th>
    <th></th>
  </tr>
 
  <% @product_pricings.each do |pricing| %>
    <tr>
      <td><%= Product.find(pricing.product_id).name %></td>
      <td><%= pricing.date_from.strftime("%Y %B %d") %></td>
      <td><%= pricing.date_to.strftime("%Y %B %d") %></td>
      <td><%= pricing.amount %></td>
      <% permitted_to? :manage, :product_pricings do %>
      	<td><%= link_to 'Edit', pricing, method: :get %></td>
      	<td><%= link_to 'Delete', pricing, method: :delete,
      	data: { confirm: 'Are you sure you want to the pricing of '+pricing.amount+' for \''+ Product.find(pricing.product_id).name+'\'?' }  %></td>
      <% end %>
      
    </tr>
  <% end %>
</table>
<p>
<%= will_paginate(@product_pricings, :previous_label => "&laquo;", :next_label => "&raquo;", :class=>"small-font", :outer_window => 1, :inner_window => 0, :class=>"small-font", :outer_window => 1, :inner_window => 0) %>
<%= page_entries_info @product_pricings %>
</p>

<% end %>

app/views/product_pricings/edit.html.erb
<%= render 'form' %>

app/views/product_pricings/index.html.erb
<%= render 'index' %>

app/views/product_pricings/new.html.erb
<%= render 'back' %>
<%= render 'form' %>

app/views/product_pricings/show.html.erb
<%= render 'back' %>
<%= render 'form' %>