config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', as: :root
  resources :users, only: [:new, :create, :show]
  resources :products, only: [:index, :new, :create, :update, :show]
  resources :accounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :accounting_periods, only: [:index, :new, :create, :update, :show, :destroy]
  resources :transaction_types, only: [:index, :new, :create, :update, :show, :destroy]
  resources :gl_mappings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_makes, only: [:index, :new, :create, :update, :show, :destroy]
  resources :vehicle_models, only: [:index, :new, :create, :update, :show, :destroy]
  resources :images, only: [:index, :new, :create, :update, :show, :destroy]

  resources :product_discounts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :product_pricings, only: [:index, :new, :create, :update, :show, :destroy]

  resources :member_profiles, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_cars, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_contacts, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_stickers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_photos, only: [:index, :new, :create, :update, :show, :destroy]
  resources :profile_car_photos, only: [:index, :new, :create, :update, :show, :destroy]
    
  resources :sequences, only: [:index, :new, :create, :update, :show, :destroy]
  resources :general_ledgers, only: [:index, :new, :create, :update, :show, :destroy]
  resources :inventories, only: [:index, :new, :create, :update, :show, :destroy]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sparesandaccessories, only: [:index, :new, :create, :update, :show, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/email_sent', to: 'email_sent#index', as: :email_sent
  get '/activate/:activation_code', to: 'activations#create', as: :activate
  get '/admin', to: 'administration#index', as: :admin
  get '/admin/listusers', to: 'administration#listusers', as: :listusers
  post '/admin/toggleactive', to: 'administration#toggleactive', as: :toggleactive
  post '/admin/toggleapprove', to: 'administration#toggleapprove', as: :toggleapprove
  post '/admin/toggleconfirm', to: 'administration#toggleconfirm', as: :toggleconfirm
  get '/gallery', to: 'gallery#index', as: :gallery
  get '/search/:object', to: 'search#search', as: :genericsearch
  get '/accountingpanel', to: 'accountingpanel#index', as: :accountingpanel
  get '/customer_view', to: 'sparesandaccessories#customer_view', as: :customer_view
  delete '/delete_pricing/:id', to: 'products#delete_pricing', as: :delete_pricing
  patch '/toggle_discount_active/:id', to: 'products#toggle_discount_active', as: :toggle_discount_active
  delete '/delete_discount/:id', to: 'products#delete_discount', as: :delete_discount
  delete '/delete_contact/:id', to: 'member_profiles#delete_contact', as: :delete_contact
  delete '/delete_profile_car/:id', to: 'member_profiles#delete_profile_car', as: :delete_profile_car
  delete 'delete_sticker/:id', to: 'member_profiles#delete_sticker', as: :delete_sticker
  get '/profile_car_view', to: 'member_profiles#profile_car_view', as: :profile_car_view
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :vehicle_models
  has_many :images
  has_many :product_pricings
  has_many :product_discounts
  
  accepts_nested_attributes_for :images
  
  validates :sku, presence: true, uniqueness: true
  attr_reader :inventory_id
  attr_writer :inventory_id
  
  attr_reader :vehicle_models
  attr_writer :vehicle_models
  
  def self.getDefaultImage
    Image.findDefaultImage(self.id)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #filter_resource_access
  #include ActionController::MimeResponds
  #include ActionController::ImplicitRender
  #before_action :all_products, only: [:index, :create]
  #respond_to :html,:js

  filter_resource_access
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @product = Product.find(params[:id])
    @product = populate_product_inventory
    @images = @product.images
    @product.vehicle_models  = ProductsVehicleModels.find_by(product: @product)
  end

  def new
    @product = Product.new
    @product.images.build
    @product.product_pricings.build
    @product.product_discounts.build
    @product.vehicle_models = []
  end

  def create

    @product = Product.new(product_params)
    if @product.save
      extract_extra_attribs
      flash[:info] = "Product saved successfully."
      redirect_to @product
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
    @product = populate_product_inventory
    @images = @product.images
    @product.vehicle_models = ProductsVehicleModels.find_by_productid @product.id
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)

      extract_extra_attribs

      flash[:success] = "Product SKU  #{@product.sku}  successfully updated!"
      redirect_to @product
    else
      render :edit
    end
  end

  def delete_pricing
    pricing = ProductPricing.find(params[:id]);
    product = pricing.product
    pricing.delete
    redirect_to product
  end
  
  def toggle_discount_active
    discount = ProductDiscount.find(params[:id]);
    discount.active  = !discount.active
    product = discount.product
    discount.save
    redirect_to product
  end
  
  def delete_discount
    discount = ProductDiscount.find(params[:id]);
    product = discount.product
    discount.delete
    redirect_to product
  end

  private

  def product_params
    params.require(:product).permit(:vehicle_model_id, :name, :sku, :count, :description, :inventory_id)
  end

  private

  def add_product_to_inventory
    inventory_id = params[:product][:inventory_id]

    inventory = Inventory.find(inventory_id)
    inventoryproduct = InventoryProduct.find_by(product: @product)#, inventory: inventory)

    if(inventoryproduct.nil?)
      inventoryproduct = InventoryProduct.new
      inventoryproduct.product = @product
    end

    inventoryproduct.inventory = inventory
    inventoryproduct.save

    @product = inventoryproduct.product
  end

  private

  def populate_product_inventory

    inventoryproduct = InventoryProduct.find_by(product: @product)
    if(!inventoryproduct.nil?)
      @inventory = inventoryproduct.inventory
      @product.inventory_id = @inventory.id
    end
    @product
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  private

  def all_products
    @products = Product.paginate(:page => params[:page], :per_page => 5)
  end

  private

  def extract_extra_attribs

    if(!params[:images].nil? && !params[:images]['avatar'].nil?)
      params[:images]['avatar'].each do |a|
        @image = @product.images.create!(:avatar => a, :product_id => @product.id)
      end
    end

    if(!params[:product].nil? && !params[:product]['vehicle_models'].nil?)
      cleanvms = params[:product]['vehicle_models']  - ["NULL"]
      cleanvms = cleanvms.reject { |c| c.empty? }
      ProductsVehicleModels.where(product: @product).where.not(vehicle_model_id: cleanvms).delete_all;
      cleanvms.each do |vm|
        if(!vm.nil? & !vm.empty?)
          vehicle_model = VehicleModel.find(vm)
          mapping  = ProductsVehicleModels.find_by(product: @product, vehicle_model: vehicle_model)
          if(mapping.nil?)
            @product_vehicle_model = ProductsVehicleModels.new
            @product_vehicle_model.product = @product
            @product_vehicle_model.vehicle_model  = vehicle_model
            @product_vehicle_model.save!
          end
        end
      end
    end

    if(!params[:product].nil? && !params[:product]['product_pricings'].nil?)
      date_from = params[:product]['product_pricings']['date_from']
      date_to = params[:product]['product_pricings']['date_to']
      if(!date_from.nil? && !date_from.nil? && !date_from.empty? && !date_from.empty?)
        product_pricing = ProductPricing.new
        product_pricing.amount = params[:product]['product_pricings']['amount']
        product_pricing.date_from = params[:product]['product_pricings']['date_from']
        product_pricing.date_to = params[:product]['product_pricings']['date_to']
        product_pricing.product = @product
        product_pricing.save!
      end
    end

    if(!params[:product].nil? && !params[:product]['product_discounts'].nil?)
      date_from = params[:product]['product_discounts']['date_from']
      date_to = params[:product]['product_discounts']['date_to']
      if(!date_from.nil? && !date_from.nil? && !date_from.empty? && !date_from.empty?)
        product_discount = ProductDiscount.new
        product_discount.percent = params[:product]['product_discounts']['percent']
        product_discount.date_from = params[:product]['product_discounts']['date_from']
        product_discount.date_to = params[:product]['product_discounts']['date_to']
        product_discount.active = params[:product]['product_discounts']['active']
        product_discount.discount_type = params[:product]['product_discounts']['discount_type']
        product_discount.product = @product
        product_discount.save!
      end
    end

    if(!params[:vehicle_models].nil?)
      params[:images]['vehicle_models'].each do |vm|
        @vehicle_model = @product.vehicle_models.create!(:product => @product, :vehicle_model => vm)
      end
    end

    @product = add_product_to_inventory
  end
end

app/views/products/_back.html.erb
<p>
<%= link_to(raw("<span class='glyphicon glyphicon-arrow-left'> Back </span>"),products_url(:page => params[:page] ),{ :class => 'btn btn-primary'})  %>
</p>

app/views/products/_discounts.html.erb
  	<a href="#discounts" class="btn btn-info" data-toggle="collapse"><span class="glyphicon glyphicon-plus"></span> Add Discounts to Product</a>
	
	<div  id="discounts"  class="collapse panel panel-primary hoctransparent p5">	
		<p>
	  		<div class="panel-heading">Produduct Discounts</div>
	  	</p>
	  	<%= f.fields_for :product_discounts do |pp| %>
	  		<p>
	  			<%= pp.number_field :percent,  class: "form-control", placeholder: "% Discount"  %>
	  		</p>
	  		<p>
	  			<%= pp.text_field :date_from, class: "datepicker_to1 form-control", placeholder: "Discount starts", "data-date-format" => "yyyy-mm-dd 00:00:00"  %>
	  		</p>
	  		<p>
	  			<%= pp.text_field :date_to, class: "datepicker_to2 form-control", placeholder: "Discount ends", "data-date-format" => "yyyy-mm-dd 23:59:59"  %>
	  		</p>
	  		
	  		<p>
		  		<div class="form-inline">
			  		
			  			<%= pp.select :discount_type, ProductDiscount.discount_types.map { |key, value| [key.humanize, key] }, {prompt: "Select Discount Type"}, {class: "form-control"} %>
			  		
			  		    <%= pp.label :active do %>
			  				Active <%= pp.check_box :active, class: "form-control" %> 
			  			<% end %>
			  		
		  		</div>
	  		</p>
	  		
	  	<% end %>
  	  	
	  	<table class="table">
		  <tr>
		    <th>% Discount</th>
		    <th>Condition</th>
		    <th>Active from</th>
		    <th>Active to</th>
		    <th>Activated</th>
		    <% permitted_to? :manage, :products do %>
		    	<th></th>
		    <% end %>
		  </tr>
		  <tbody>
	  		<% @product.product_discounts.each do |pp| %>
		  		<% if(!pp.id.nil?) %>
		  			<tr>
			  			<td ><%= number_with_precision(pp.percent, :precision => 2, :delimiter => ',') %> % </td>
			  			<td><%= pp.discount_type.humanize %></td>
			  			<td><%= pp.date_from.strftime("%Y %B %d") %></td>
			  			<td><%= pp.date_to.strftime("%Y %B %d") %></td>
			  			<td><%= pp.active %></td>
			  			<% permitted_to? :manage, :products do %>
			  			    <% 
			  			    	glyphicon_class = 'glyphicon-ban-circle'
			  			    	buton_string = 'Disable'
			  			    	if(!pp.active)
			  			    		glyphicon_class = 'glyphicon-ok-circle'
			  			    		buton_string = 'Enable'
			  			    	end
			  			    	
			  			    %>
			  			  	<td><%= link_to "<span class='glyphicon #{glyphicon_class}'> #{buton_string}</span>".html_safe,  product_discount_path(:id => pp.id), method: :patch,
			      			data: { confirm: "Are you sure you want to #{buton_string} "+number_with_precision(pp.percent, :precision => 2, :delimiter => ',')+"% discount, for '"+@product.name+"' ?"} %>
			      			| <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, pp, method: :delete,
			      			data: { confirm: "Are you sure you want to delete the discount "+number_with_precision(pp.percent, :precision => 2, :delimiter => ',')+", for "+@product.name+"'?"} %></td>
					     <% end %>
				    </tr>
		  		<% end %>
	  		<% end %>
	  		</tbody>
	  	</table>
  	
  	</div>

app/views/products/_form.html.erb
<h1 class="hocheaders">Product Details</h1>

<%= form_for @product, :html => { :multipart => true } do |f| %>
	
	<%= render 'shared/errors', object: @product %>  

  <p>
    <%  
       gen_sku = getSeq("SKU")
      %>
    <%= f.collection_select :vehicle_models, [] , :id,:text, {}, {:multiple => true,  autofocus: 'true', class: 'form-control myselectss', id: 'vehicle_model', "data-tags" => "true"} %>
  </p>
   <p>
    <%= f.text_field :name,  class: "form-control", placeholder: "Product Name", required: true %>
  </p>
  <p>
    <%= f.text_field :sku, value: ( (@product.sku.nil? || @product.sku.empty?)  ? gen_sku : @product.sku),  class: "form-control", placeholder: "SKU", readonly: true  %>
  </p>
  <p>
    <%= f.number_field :count,  class: "form-control", placeholder: "Initial Quantity"  %>
  </p>
   
  <p>
    <%= f.collection_select :inventory_id, Inventory.all, :id,:name, {prompt: "Select an Inventory"}, {class: "form-control", required: true} %>
  </p>
  <p>
    <%= f.text_area :description,  class: "form-control", placeholder: "Description"  %>
  </p>
  
  <p>
    <%= f.file_field :avatar, name: "images[avatar][]", :multiple => true, class: "form-control", placeholder: "Add images"  %>
  </p>
  
  <p>
  	<%= render 'pricings', f: f, product: @product  %>
  </p>
  
  <p>
  	<%= render 'discounts', f: f, product: @product  %>
  	
  </p>
  
  <p><%= f.submit "Save", class: "btn btn-lg btn-primary btn-block btn-signin" %></p>
<% end %>


<h1 class="hocheaders">Images</h1>

<% if(!@images.nil? && @images.respond_to?(:each)) %>
	<% counter = 0
	   count_per_row = 3 %>
	<% @images.each do |p| %>
		 <% remainder = counter%count_per_row
		   	new_row = remainder==0
		   	counter = counter+1 %>  
		   		
		   	<%  if(new_row || counter==0) %>
				  <div class="row">
			<%  end %>
			
					<div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
					
						<div>
					  		<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, p, method: :delete,
				      		data: { confirm: 'Are you sure you want to  delete this image \''+p.avatar_url+'\' ?' }  %>
					  	</div>
					  	    	
						<div class="thumbnail">
							<div class="thumb" style="overflow:hidden; position:relative; min-height: 50px; max-height: 150px;" >
						  	    <div class="thumb" style="overflow:hidden; position:relative; min-height: 50px; max-height: 150px;" >
						  	    	<%= image_tag p.avatar.url, :class => "img-responsive" %>
						  	    </div>
					  	    
					  		</div>
					  	</div>
					</div>
					<div class="clearfix visible-xs"></div>
			<%  if(counter==count_per_row)
					counter = 0 %>
				  </div>
			<%  end %>
	<% end %>		  	
<% end %> 

<script type="text/javascript">

$(document).ready(function(){
    $('.datepicker_to1').datepicker();
    $('.datepicker_to2').datepicker();
  });
product_id = ("<%= @product.id %>");
 var x = $( '.myselectss' ).select2({
    	theme: "bootstrap",
    	placeholder: 'Type to Search Vehicle Model...',
  		allowClear: false,
    	tags: true,
    	vehicle_models: [],
    	multiple: true,
    	initSelection: function(element, callback) {
    		//console.log("we've called init!");
    		$.ajax({
    			url: '/search/vehicle_model?product_id='+product_id, 
		        dataType: 'json', 
    			data: function (params) {
			      return {
			        product_id: product_id
			      };
			    }/*,
			    cache: false,
	    		escapeMarkup: function (markup) { 
	    			return markup; 
	    		}*/
			}).done(function(data) { 
					$.each(data, function(idx, val) {
					
				        data[idx].text = val.name;
				        $('#vehicle_model').append(
				        	$('<option>', { 
					        	value: val.id,
					        	text : val.text 
					    	})
					    );
				        $('select#vehicle_model option[value='+val.id+']').attr('selected','selected');
				        
				        //$(".select2-selection__choice__remove").click(function (e) { alert('hi'); }); 
				    });
		            callback(data);
		      });
    		//callback({"id": 5, "text":"myValue"});
    	}, 
    	ajax: {
			url: '/search/vehicle_model',
			delay: 250,
			data: function (params) {
		      return {
		        q: params.term, // search term
		        page: params.page
		      };
		    },
			processResults: function (data, params) {
				params.page = params.page || 1;
			    data = JSON.parse(data);
			    $.each(data, function(idx, val) {
			        data[idx].text = val.name;
			    });
			    return {
			        results: data,
			        pagination: {
			          more: (params.page * 30) < data.total_count
			        }
				}
			}
		},	
    	createSearchChoice: function (term, data){
    		console.log(data);
    		console.log(term);
    	},
    	insertTag: function (data, tag) {
	    	// Insert the tag at the end of the results
	    	//data.push(tag);
	  	}
});


</script>

app/views/products/_pricings.html.erb
  	<h2><a href="#pricings" class="btn btn-info" data-toggle="collapse"><span class="glyphicon glyphicon-plus"></span> Add Pricing to Product</a></h2>
	
	<div  id="pricings"  class="collapse panel panel-primary hoctransparent p5">	
  	
  	<p>
  		<div class="panel-heading">Product Pricing</div>
  	</p>
  	
  	<%= f.fields_for :product_pricings do |pp| %>
  		<p>
  			<%= pp.number_field :amount,  class: "form-control", placeholder: "Price"  %>
  		</p>
  		<p>
  			<%= pp.text_field :date_from, class: "datepicker_to1 form-control", placeholder: "Price Active From", "data-date-format" => "yyyy-mm-dd 00:00:00"  %>
  		</p>
  		<p>
  			<%= pp.text_field :date_to, class: "datepicker_to2 form-control", placeholder: "Up To", "data-date-format" => "yyyy-mm-dd 23:59:59"  %>
  		</p>
  	<% end %>
  	
  	
  	<table class="table">
	  <tr>
	    <th>Price</th>
	    <th>Active from</th>
	    <th>Active to</th>
	    <% permitted_to? :manage, :products do %>
	    	<th></th>
	    <% end %>
	  </tr>
	  <tbody>
  		<% @product.product_pricings.each do |pp| %>
	  		<% if(!pp.id.nil?) %>
	  			<tr>
		  			<td ><%= number_with_precision(pp.amount, :precision => 2, :delimiter => ',') %></td>
		  			<td><%= pp.date_from.strftime("%Y %B %d") %></td>
		  			<td><%= pp.date_to.strftime("%Y %B %d") %></td>
		  			<% permitted_to? :manage, :products do %>
		  			<td><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, pp, method: :delete,
		      		data: { confirm: 'Are you sure you want to  delete the pricing \''+number_with_precision(pp.amount, :precision => 2, :delimiter => ',')+'\', for \''+@product.name+'\'?'} %></td>
				     <% end %>
				    <% end %>
	  			</tr>
  		<% end %>
  		</tbody>
  	</table>
  	
  	</div>

app/views/products/_product.html.erb
<tr>
      <td><%= product.sku %></td>
      <td><%= product.name %></td>
      <td><%= product.count %></td>
      <% permitted_to? :manage, :products do %>
      	<td><%= link_to 'Edit', product, method: :get %></td>
      <% end %>
</tr>

app/views/products/create.html.erb
<%= render @products %>

app/views/products/edit.html.erb
<%= render 'back' %>
<%= render 'imageupload' %>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>
<% permitted_to? :manage, :products do %>
<%= link_to 'New Product', new_product_url %>
<% end %>
<% @products = Product.paginate(:page => params[:page], :per_page => 5) %>
<table class="table table-hover">
  <tr>
    <th>SKU</th>
    <th>Name</th>
    <th>Stock Qty</th>
    <% permitted_to? :manage, :products do %>
    	<th></th>
    <% end %>
  </tr>
 
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.sku %></td>
      <td><%= product.name %></td>
      <td><%= product.count %></td>
      <% permitted_to? :manage, :products do %>
      	<td><%= link_to 'Edit', product_url(:id => product.id, :page => params[:page]), method: :get %></td>
      <% end %>
  
    </tr>
  <% end %>
</table>

<p>
<%= will_paginate(@products, :previous_label => "&laquo;", :next_label => "&raquo;", :class=>"small-font", :outer_window => 1, :inner_window => 0, :class=>"small-font", :outer_window => 1, :inner_window => 0) %>
<%= page_entries_info @products %>
</p>

app/views/products/oldnew.html.erb
<%= render 'back' %>
<%= render 'form' %>